# Generated by Django 2.0.4 on 2018-10-19 18:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_mail', models.CharField(max_length=100, verbose_name='post_mail')),
                ('post_text', models.CharField(default='', max_length=100, verbose_name='post_text')),
                ('post_content', ckeditor.fields.RichTextField(verbose_name='content')),
            ],
        ),
    ]
