# Generated by Django 2.0.4 on 2018-10-19 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=200)),
                ('letter', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.Letter')),
            ],
        ),
    ]
