# Generated by Django 2.0.4 on 2018-10-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_a', models.CharField(max_length=100)),
                ('content_a', models.TextField()),
            ],
        ),
    ]
