# Generated by Django 2.0.4 on 2018-10-21 18:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_mail',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_text',
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='content_a',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_a',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
