# Generated by Django 2.0.4 on 2018-10-22 20:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_l', models.CharField(max_length=100)),
                ('content_l', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
