# Generated by Django 2.0.4 on 2018-10-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_learn'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='word_exp',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
